name: 'Trigger-Binder-build'
on:
  push:
    branches:
      - <binder-branch>

jobs:
  trigger-binder-build:
    runs-on: ubuntu-latest
    steps:
      - uses: s-weigand/trigger-mybinder-build@v1
        with:
          target-repo: APN-Pucky/pyhep-2023
          service-name: gh
          target-state: HEAD
          use-default-build-servers: false
          additional-build-servers: |
            binderhub.ssl-hep.org
          debug: true